version: "3.7"
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voting
      MYSQL_USER: chandu
      MYSQL_PASSWORD: chandu
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
